/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import Controller.Pokemon.Pokemon;
import Model.Load;
import static Model.Load.tipos;
import static Model.Load.pokedex;
import static Model.Load.especies;
import static Model.Load.te;
import static Model.Load.tp;
import static Model.Pesquisa.Pesquisa.re;
import static Model.Load.hb;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import Model.Pesquisa.*;
import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kainan
 */
public class Interface1 extends javax.swing.JFrame {

   
    public static Load model = new Load();
    public static Pesquisa busca = new Pesquisa();

    /**
     * Creates new form Interface1
     */

    public Interface1() {
        initComponents();
        setSize(1388, 768);
        jFramePesquisa.setSize(1388, 768);
        setLocationRelativeTo(null);
        setResizable(false);
        jInternalFrame1.setVisible(false);
       
        model.csv();
       
       
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(te));
        jComboTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(tp));
        jComboTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(tp));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(te));
        jComboTipo3.setModel(new javax.swing.DefaultComboBoxModel<>(tp));
        jComboTipo4.setModel(new javax.swing.DefaultComboBoxModel<>(tp));
        jComboBox1.setVisible(false);
        jComboBox3.setVisible(false);
                
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFramePesquisa = new javax.swing.JFrame();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jTextId1 = new javax.swing.JTextField();
        jComboTipo3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboTipo4 = new javax.swing.JComboBox<>();
        jTextAltura1 = new javax.swing.JTextField();
        jTextPeso1 = new javax.swing.JTextField();
        jLabelPeso2 = new javax.swing.JLabel();
        jLabelAltura2 = new javax.swing.JLabel();
        jLabeNome1 = new javax.swing.JLabel();
        jLabelTipo3 = new javax.swing.JLabel();
        jLabelCat1 = new javax.swing.JLabel();
        jLabelHabitat1 = new javax.swing.JLabel();
        bCadastrar1 = new javax.swing.JButton();
        bImagem1 = new javax.swing.JButton();
        lImagem1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabelID1 = new javax.swing.JLabel();
        jTextNome1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextDesc1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jFramePesquisaEspecie = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        jLabelPesqNome = new javax.swing.JLabel();
        jTextFieldPesqNome = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabelAltura3 = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        bMenu1 = new javax.swing.JButton();
        jLabelTipo4 = new javax.swing.JLabel();
        jLabelPeso3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabelCTipo3 = new javax.swing.JLabel();
        jLabelCPeso1 = new javax.swing.JLabel();
        jLabelDec1 = new javax.swing.JLabel();
        jLabelTipo5 = new javax.swing.JLabel();
        JlabellImage1 = new javax.swing.JLabel();
        jLabelCNome1 = new javax.swing.JLabel();
        bBack1 = new javax.swing.JButton();
        jLabelCId1 = new javax.swing.JLabel();
        jLabelEspecie1 = new javax.swing.JLabel();
        bNext1 = new javax.swing.JButton();
        jLabelCTipo4 = new javax.swing.JLabel();
        jLabelId1 = new javax.swing.JLabel();
        jLabelCAltura1 = new javax.swing.JLabel();
        jLabelCEspecie1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextCDesc1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListaNome = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabelCHabitat = new javax.swing.JLabel();
        jButtonClasse = new javax.swing.JButton();
        jButtonEspecie = new javax.swing.JButton();
        jButtonNome = new javax.swing.JButton();
        jButtonHabitat = new javax.swing.JButton();
        jButtonMenu = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabelAltura1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        bMenu = new javax.swing.JButton();
        jLabelTipo2 = new javax.swing.JLabel();
        jLabelPeso1 = new javax.swing.JLabel();
        jLabelCTipo2 = new javax.swing.JLabel();
        jLabelCPeso = new javax.swing.JLabel();
        jLabelDec = new javax.swing.JLabel();
        jLabelTipo1 = new javax.swing.JLabel();
        JlabellImage = new javax.swing.JLabel();
        jLabelCNome = new javax.swing.JLabel();
        bBack = new javax.swing.JButton();
        jLabelCId = new javax.swing.JLabel();
        jLabelEspecie = new javax.swing.JLabel();
        bNext = new javax.swing.JButton();
        jLabelCTipo1 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelCAltura = new javax.swing.JLabel();
        jLabelCEspecie = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextCDesc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabelCHabitat1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTextId = new javax.swing.JTextField();
        jComboTipo2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboTipo1 = new javax.swing.JComboBox<>();
        jTextAltura = new javax.swing.JTextField();
        jTextPeso = new javax.swing.JTextField();
        jLabelPeso = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabeNome = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelCat = new javax.swing.JLabel();
        jLabelHabitat = new javax.swing.JLabel();
        bCadastrar = new javax.swing.JButton();
        bImagem = new javax.swing.JButton();
        lImagem = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDesc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        jFramePesquisa.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFramePesquisa.getContentPane().setLayout(null);

        jInternalFrame3.setBorder(null);
        jInternalFrame3.setClosable(true);
        jInternalFrame3.setTitle("Alterar");
        jInternalFrame3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame3.setVisible(false);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semente", "Gás", " " }));

        jComboTipo4.setToolTipText("");
        jComboTipo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipo4ActionPerformed(evt);
            }
        });

        jTextAltura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAltura1ActionPerformed(evt);
            }
        });

        jLabelPeso2.setText("PESO");

        jLabelAltura2.setText("ALTURA");

        jLabeNome1.setText("NOME");

        jLabelTipo3.setText("TIPO");

        jLabelCat1.setText("CATEGORIAS");

        jLabelHabitat1.setText("HABITAT");

        bCadastrar1.setText("ATUALIZAR");
        bCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrar1ActionPerformed(evt);
            }
        });

        bImagem1.setText("IMAGEM");
        bImagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImagem1ActionPerformed(evt);
            }
        });

        lImagem1.setBackground(new java.awt.Color(255, 255, 255));
        lImagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton7.setText("CANCELAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabelID1.setText("ID");

        jTextDesc1.setColumns(20);
        jTextDesc1.setRows(5);
        jScrollPane4.setViewportView(jTextDesc1);

        jLabel5.setText("Descrição");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabeNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addComponent(jLabelTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextId1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                    .addComponent(jComboTipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jComboTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                            .addComponent(jTextNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelHabitat1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                    .addComponent(jTextPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(bCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69))))
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboTipo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitat1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAltura2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(bCadastrar1)))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(lImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bImagem1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jFramePesquisa.getContentPane().add(jInternalFrame3);
        jInternalFrame3.setBounds(100, 40, 810, 480);

        jFramePesquisaEspecie.setClosable(true);
        jFramePesquisaEspecie.setTitle("Pesquisa Por Nome");
        jFramePesquisaEspecie.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Pesquisa Por Nome");

        jLabelPesqNome.setText("Nome");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jFramePesquisaEspecieLayout = new javax.swing.GroupLayout(jFramePesquisaEspecie.getContentPane());
        jFramePesquisaEspecie.getContentPane().setLayout(jFramePesquisaEspecieLayout);
        jFramePesquisaEspecieLayout.setHorizontalGroup(
            jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFramePesquisaEspecieLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabelPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBox1, 0, 134, Short.MAX_VALUE)
                        .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextFieldPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel4))
                    .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButtonPesquisar)
                        .addGap(60, 60, 60)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFramePesquisaEspecieLayout.setVerticalGroup(
            jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                        .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                                .addContainerGap(88, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(jFramePesquisaEspecieLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPesqNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jFramePesquisaEspecieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPesquisar)
                            .addComponent(jButton3))))
                .addGap(26, 26, 26))
        );

        jFramePesquisa.getContentPane().add(jFramePesquisaEspecie);
        jFramePesquisaEspecie.setBounds(40, 80, 530, 320);

        jInternalFrame4.setBorder(null);
        jInternalFrame4.setClosable(true);
        jInternalFrame4.setTitle("Pokemons");
        jInternalFrame4.setVisible(false);
        jInternalFrame4.getContentPane().setLayout(null);

        jLabel18.setText("Imagem");
        jInternalFrame4.getContentPane().add(jLabel18);
        jLabel18.setBounds(137, 217, 81, 31);

        jLabelAltura3.setText("Altura");
        jInternalFrame4.getContentPane().add(jLabelAltura3);
        jLabelAltura3.setBounds(550, 140, 43, 31);

        jLabelNome1.setText("Nome");
        jInternalFrame4.getContentPane().add(jLabelNome1);
        jLabelNome1.setBounds(358, 102, 47, 30);

        bMenu1.setText("MENU");
        bMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenu1ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(bMenu1);
        bMenu1.setBounds(560, 30, 80, 23);

        jLabelTipo4.setText("Tipo2");
        jInternalFrame4.getContentPane().add(jLabelTipo4);
        jLabelTipo4.setBounds(555, 183, 41, 33);

        jLabelPeso3.setText("Peso");
        jInternalFrame4.getContentPane().add(jLabelPeso3);
        jLabelPeso3.setBounds(358, 143, 47, 26);

        jButton5.setText("EDITAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(jButton5);
        jButton5.setBounds(650, 30, 100, 23);
        jInternalFrame4.getContentPane().add(jLabelCTipo3);
        jLabelCTipo3.setBounds(615, 183, 160, 33);
        jInternalFrame4.getContentPane().add(jLabelCPeso1);
        jLabelCPeso1.setBounds(417, 146, 132, 31);

        jLabelDec1.setText("Descrição");
        jInternalFrame4.getContentPane().add(jLabelDec1);
        jLabelDec1.setBounds(359, 260, 90, 25);

        jLabelTipo5.setText("Tipo1");
        jInternalFrame4.getContentPane().add(jLabelTipo5);
        jLabelTipo5.setBounds(358, 180, 47, 33);

        JlabellImage1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlabellImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttait/blogsbot/com/Images/1.png")));
        jInternalFrame4.getContentPane().add(JlabellImage1);
        JlabellImage1.setBounds(70, 34, 196, 172);
        jInternalFrame4.getContentPane().add(jLabelCNome1);
        jLabelCNome1.setBounds(417, 105, 132, 30);

        bBack1.setText("<");
        bBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBack1ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(bBack1);
        bBack1.setBounds(437, 26, 41, 23);
        jInternalFrame4.getContentPane().add(jLabelCId1);
        jLabelCId1.setBounds(620, 100, 92, 30);

        jLabelEspecie1.setText("Especie");
        jInternalFrame4.getContentPane().add(jLabelEspecie1);
        jLabelEspecie1.setBounds(360, 230, 47, 23);

        bNext1.setText(">");
        bNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNext1ActionPerformed(evt);
            }
        });
        jInternalFrame4.getContentPane().add(bNext1);
        bNext1.setBounds(496, 26, 41, 23);
        jInternalFrame4.getContentPane().add(jLabelCTipo4);
        jLabelCTipo4.setBounds(400, 180, 132, 33);

        jLabelId1.setText("ID");
        jInternalFrame4.getContentPane().add(jLabelId1);
        jLabelId1.setBounds(560, 100, 32, 27);
        jInternalFrame4.getContentPane().add(jLabelCAltura1);
        jLabelCAltura1.setBounds(635, 146, 92, 31);
        jInternalFrame4.getContentPane().add(jLabelCEspecie1);
        jLabelCEspecie1.setBounds(417, 222, 132, 30);

        jTextCDesc1.setEditable(false);
        jTextCDesc1.setColumns(20);
        jTextCDesc1.setRows(5);
        jScrollPane5.setViewportView(jTextCDesc1);

        jInternalFrame4.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(359, 296, 283, 96);

        jListaNome.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jListaNome);

        jInternalFrame4.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(70, 266, 176, 147);

        jLabel2.setText("Habitat");
        jInternalFrame4.getContentPane().add(jLabel2);
        jLabel2.setBounds(555, 222, 48, 30);
        jInternalFrame4.getContentPane().add(jLabelCHabitat);
        jLabelCHabitat.setBounds(617, 222, 150, 30);

        jFramePesquisa.getContentPane().add(jInternalFrame4);
        jInternalFrame4.setBounds(40, 170, 810, 440);

        jButtonClasse.setBackground(new java.awt.Color(0, 153, 255));
        jButtonClasse.setText(" POR CLASSE");
        jButtonClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClasseActionPerformed(evt);
            }
        });
        jFramePesquisa.getContentPane().add(jButtonClasse);
        jButtonClasse.setBounds(860, 230, 180, 40);

        jButtonEspecie.setBackground(new java.awt.Color(255, 204, 0));
        jButtonEspecie.setText("POR ESPÉCIE");
        jButtonEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspecieActionPerformed(evt);
            }
        });
        jFramePesquisa.getContentPane().add(jButtonEspecie);
        jButtonEspecie.setBounds(290, 230, 180, 40);

        jButtonNome.setBackground(new java.awt.Color(0, 153, 0));
        jButtonNome.setText(" POR NOME");
        jButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNomeActionPerformed(evt);
            }
        });
        jFramePesquisa.getContentPane().add(jButtonNome);
        jButtonNome.setBounds(480, 230, 180, 40);

        jButtonHabitat.setBackground(new java.awt.Color(255, 102, 0));
        jButtonHabitat.setText("POR HABITAT");
        jButtonHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHabitatActionPerformed(evt);
            }
        });
        jFramePesquisa.getContentPane().add(jButtonHabitat);
        jButtonHabitat.setBounds(670, 230, 180, 40);

        jButtonMenu.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMenu.setText("MENU");
        jButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuActionPerformed(evt);
            }
        });
        jFramePesquisa.getContentPane().add(jButtonMenu);
        jButtonMenu.setBounds(580, 470, 190, 40);

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabelTitulo.setText("PESQUISA DE POKEMONS");
        jFramePesquisa.getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(380, 160, 580, 40);

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tela4.png"))); // NOI18N
        fundo.setMaximumSize(new java.awt.Dimension(1366, 786));
        fundo.setMinimumSize(new java.awt.Dimension(1366, 786));
        jFramePesquisa.getContentPane().add(fundo);
        fundo.setBounds(0, -80, 1750, 900);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POOKEDEX");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrame2.setBorder(null);
        jInternalFrame2.setClosable(true);
        jInternalFrame2.setTitle("Pokemons");
        jInternalFrame2.setVisible(false);

        jLabel17.setText("Imagem");

        jLabelAltura1.setText("Altura");

        jLabelNome.setText("Nome");

        bMenu.setText("MENU");
        bMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenuActionPerformed(evt);
            }
        });

        jLabelTipo2.setText("Tipo2");

        jLabelPeso1.setText("Peso");

        jLabelDec.setText("Descrição");

        jLabelTipo1.setText("Tipo1");

        JlabellImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlabellImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ttait/blogsbot/com/Images/1.png")));

        bBack.setText("<");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        jLabelEspecie.setText("Especie");

        bNext.setText(">");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });

        jLabelId.setText("ID");

        jTextCDesc.setEditable(false);
        jTextCDesc.setColumns(20);
        jTextCDesc.setRows(5);
        jScrollPane2.setViewportView(jTextCDesc);

        jLabel6.setText("Habitat");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(JlabellImage, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelCPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCEspecie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabelCTipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabelAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCId, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCHabitat1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDec)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                    .addGap(358, 358, 358)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(bBack)
                                .addGap(18, 18, 18)
                                .addComponent(bNext)
                                .addGap(18, 18, 18)
                                .addComponent(bMenu))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(jLabelId)))
                        .addComponent(jLabelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame2Layout.createSequentialGroup()
                            .addComponent(jLabelTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156)
                            .addComponent(jLabelTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(169, Short.MAX_VALUE)))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(JlabellImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelCNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jLabelCAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelCTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelAltura1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelCTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCHabitat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addComponent(jLabelDec, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bBack)
                        .addComponent(bNext)
                        .addComponent(bMenu))
                    .addGap(51, 51, 51)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelId))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );

        getContentPane().add(jInternalFrame2);
        jInternalFrame2.setBounds(40, 170, 771, 437);

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Cadastrar");
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setVisible(false);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semente", "Gás", " " }));

        jComboTipo1.setToolTipText("");
        jComboTipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipo1ActionPerformed(evt);
            }
        });

        jTextAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlturaActionPerformed(evt);
            }
        });

        jLabelPeso.setText("PESO");

        jLabelAltura.setText("ALTURA");

        jLabeNome.setText("NOME");

        jLabelTipo.setText("TIPO");

        jLabelCat.setText("CATEGORIAS");

        jLabelHabitat.setText("HABITAT");

        bCadastrar.setText("CADASTRAR");
        bCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastrarActionPerformed(evt);
            }
        });

        bImagem.setText("IMAGEM");
        bImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImagemActionPerformed(evt);
            }
        });

        lImagem.setBackground(new java.awt.Color(255, 255, 255));
        lImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton6.setText("CANCELAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelID.setText("ID");

        jTextDesc.setColumns(20);
        jTextDesc.setRows(5);
        jScrollPane1.setViewportView(jTextDesc);

        jLabel3.setText("Descrição");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(jComboTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(jComboTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(jTextPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(bCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69))))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(bCadastrar)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bImagem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(100, 40, 810, 480);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("POKEMONS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 210, 220, 50);

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setText("CADASTRAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(590, 460, 150, 60);

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setText("BUSCA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 210, 230, 50);

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 48)); // NOI18N
        jLabel1.setText("POOKEDEX");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 80, 340, 120);

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/tela4.png"))); // NOI18N
        imagen.setMaximumSize(new java.awt.Dimension(1388, 768));
        imagen.setMinimumSize(new java.awt.Dimension(1388, 768));
        getContentPane().add(imagen);
        imagen.setBounds(0, -60, 1420, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = 0;
        if (pokedex.size() > 0) {
            JlabellImage.setIcon(null);
            jInternalFrame2.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Não existem Pokemons Cadastrados");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jFramePesquisa.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jInternalFrame1.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed

        if (j < 0 || j == pokedex.size()) {
            j = 0;

        }
        if (j >= 0 && j < pokedex.size()) {
            
            JlabellImage.setIcon(pokedex.get(j).getFoto());
            jLabelCId.setText(String.valueOf(pokedex.get(j).getId()));
            jLabelCNome.setText(pokedex.get(j).getNome());
            jLabelCAltura.setText(String.valueOf(pokedex.get(j).getAltura()));
            jLabelCPeso.setText(String.valueOf(pokedex.get(j).getPeso()));
            jLabelCTipo1.setText(pokedex.get(j).getTipo1().getTipo());
            jLabelCTipo2.setText(pokedex.get(j).getTipo2().getTipo());
            jLabelCEspecie.setText(pokedex.get(j).getCategoria().getCategoria());
            jTextCDesc.setText(pokedex.get(j).getDesc());
            jLabelCHabitat1.setText(pokedex.get(j).getTipo1().getHabitat());
            
            j++;
        }
    }//GEN-LAST:event_bNextActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed

        if (j >= pokedex.size() || j < 0) {
            j = pokedex.size() - 1;
        }
        if (j >= 0 && j < pokedex.size()) {

            JlabellImage.setIcon(pokedex.get(j).getFoto());
            jLabelCId.setText(String.valueOf(pokedex.get(j).getId()));
            jLabelCNome.setText(pokedex.get(j).getNome());
            jLabelCAltura.setText(String.valueOf(pokedex.get(j).getAltura()));
            jLabelCPeso.setText(String.valueOf(pokedex.get(j).getPeso()));
            jLabelCTipo1.setText(pokedex.get(j).getTipo1().getTipo());
            jLabelCTipo2.setText(pokedex.get(j).getTipo2().getTipo());
            jLabelCEspecie.setText(pokedex.get(j).getCategoria().getCategoria());
            jTextCDesc.setText(pokedex.get(j).getDesc());
            jLabelCHabitat1.setText(pokedex.get(j).getTipo1().getHabitat());
            
            j--;
        }

    }//GEN-LAST:event_bBackActionPerformed

    private void bMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenuActionPerformed
        JlabellImage.setIcon(null);
        jInternalFrame2.setVisible(false);
    }//GEN-LAST:event_bMenuActionPerformed

    private void jButtonClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClasseActionPerformed
        jLabel4.setText("Pesquisa Por Classe");
        jLabelPesqNome.setText("Classes");
        jTextFieldPesqNome.setVisible(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(tp));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(tp));
        jComboBox3.setVisible(true);
        jComboBox1.setVisible(true);

        jFramePesquisaEspecie.setVisible(true);


    }//GEN-LAST:event_jButtonClasseActionPerformed

    private void jButtonEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspecieActionPerformed
        jLabel4.setText("Pesquisa Por Especie");
        jLabelPesqNome.setText("Especie");
        jTextFieldPesqNome.setVisible(false);
        jComboBox3.setVisible(false);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(te));
        jComboBox1.setVisible(true);

        jFramePesquisaEspecie.setVisible(true);
    }//GEN-LAST:event_jButtonEspecieActionPerformed

    private void jButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNomeActionPerformed
        jLabel4.setText("Pesquisa Por Nome");
        jLabelPesqNome.setText("Nome");
        jFramePesquisaEspecie.setVisible(true);
        jTextFieldPesqNome.setVisible(true);
        jComboBox3.setVisible(false);
        jComboBox1.setVisible(false);
        jTextFieldPesqNome.setText("");
    }//GEN-LAST:event_jButtonNomeActionPerformed

    private void jButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuActionPerformed
        jFramePesquisa.setVisible(false);
        this.setVisible(true);

    }//GEN-LAST:event_jButtonMenuActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        jFramePesquisaEspecie.setVisible(false);
        JlabellImage1.setIcon(null);
        if(jLabelPesqNome.getText().equals("Habitates"))
        {
            jListaNome.setListData(busca.pesquisaHabitat(jComboBox1.getItemAt(jComboBox1.getSelectedIndex())));
        }
        if (jLabelPesqNome.getText().equals("Classes") ) {
            jListaNome.setListData(busca.pesquisaEspecie(jComboBox1.getItemAt(jComboBox1.getSelectedIndex())));

        }
        if (jComboBox3.isVisible() && jComboBox1.isVisible()) {
            jListaNome.setListData(busca.pesquisaClasse(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()), jComboBox3.getItemAt(jComboBox3.getSelectedIndex())));
        }
        if (jTextFieldPesqNome.isVisible()) {
            jListaNome.setListData(busca.pesquisaNome(jTextFieldPesqNome.getText()));
        }
        if (re.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nenhum pokemon encontrado");
        } else {
            jInternalFrame4.setVisible(true);
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFramePesquisaEspecie.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jInternalFrame1.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImagemActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("ESCOLHER");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("imagem", "jpg", "png");

        file.setFileFilter(filter);
        int retorno = file.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            File filecho = file.getSelectedFile();
            ImageIcon img = new ImageIcon(filecho.getPath());
            img.setImage(img.getImage().getScaledInstance(214, 231, 0));
            lImagem.setIcon(img);

        }
    }//GEN-LAST:event_bImagemActionPerformed

    private void bCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrarActionPerformed
        try {

            Pokemon poke = new Pokemon(Integer.parseInt(jTextId.getText()), jTextNome.getText(), Float.parseFloat(jTextPeso.getText()), Float.parseFloat(jTextAltura.getText()), tipos.get(jComboTipo2.getSelectedIndex()), tipos.get(jComboTipo1.getSelectedIndex()), especies.get(jComboBox2.getSelectedIndex()), lImagem.getIcon(), jTextDesc.getText());
            poke.getTipo1().setHabitat(jTextField2.getText());
            System.out.println(poke);

            for (Pokemon pokemon : pokedex) {
                if (pokemon.getId() == poke.getId()) {
                    throw new Exception("Pokemon Já Cadastrado");

                }
            }

            pokedex.add(poke);
            JOptionPane.showMessageDialog(rootPane, "Pokemon Cadastrado");
            jTextAltura.setText("");
            jTextId.setText("");
            jTextNome.setText("");
            jTextPeso.setText("");
            jTextCDesc.setText("");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Pokemon\n Campo com Formato Inválido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Pokemon\n Preencha todos os Campos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Pokemon\n" + e.getMessage());
        }
    }//GEN-LAST:event_bCadastrarActionPerformed

    private void jTextAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlturaActionPerformed

    private void jComboTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipo1ActionPerformed

    }//GEN-LAST:event_jComboTipo1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboTipo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipo4ActionPerformed

    private void jTextAltura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAltura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAltura1ActionPerformed

    private void bCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastrar1ActionPerformed
        try {

            Pokemon poke = new Pokemon(Integer.parseInt(jTextId1.getText()), jTextNome1.getText(), Float.parseFloat(jTextPeso1.getText()), Float.parseFloat(jTextAltura1.getText()), tipos.get(jComboTipo4.getSelectedIndex()), tipos.get(jComboTipo3.getSelectedIndex()), especies.get(jComboBox4.getSelectedIndex()), lImagem1.getIcon(), jTextDesc1.getText());
            System.out.println(poke);
            poke.getTipo1().setHabitat(jTextField3.getText());
            pokedex.set(j,poke);
            JOptionPane.showMessageDialog(rootPane, "Pokemon Cadastrado");
            jTextAltura1.setText("");
            jTextId1.setText("");
            jTextNome1.setText("");
            jTextPeso1.setText("");
            jTextCDesc1.setText("");
            
            lImagem.setIcon(null);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Pokemon\n Campo com Formato Inválido");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Pokemon\n Preencha todos os Campos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Cadastrar Pokemon\n" + e.getMessage());
        }
    

    }//GEN-LAST:event_bCadastrar1ActionPerformed

    private void bImagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImagem1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("ESCOLHER");
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("imagem", "jpg", "png");

        file.setFileFilter(filter);
        int retorno = file.showOpenDialog(this);

        if (retorno == JFileChooser.APPROVE_OPTION) {
            File filecho = file.getSelectedFile();
            ImageIcon img = new ImageIcon(filecho.getPath());
            img.setImage(img.getImage().getScaledInstance(214, 231, 0));
            lImagem1.setIcon(img);

        }
    }//GEN-LAST:event_bImagem1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jInternalFrame3.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHabitatActionPerformed
        jLabel4.setText("Pesquisa Por Habitat");
        jLabelPesqNome.setText("Habitates");
        jTextFieldPesqNome.setVisible(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(hb));
        jComboBox1.setVisible(true);

        jFramePesquisaEspecie.setVisible(true);
    }//GEN-LAST:event_jButtonHabitatActionPerformed

    private void bNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNext1ActionPerformed

        if (j < 0 || j == re.size()) {
            j = 0;

        }
        if (j >= 0 && j < re.size()) {

            JlabellImage1.setIcon(re.get(j).getFoto());
            jLabelCId1.setText(String.valueOf(re.get(j).getId()));
            jLabelCNome1.setText(re.get(j).getNome());
            jLabelCAltura1.setText(String.valueOf(re.get(j).getAltura()));
            jLabelCPeso1.setText(String.valueOf(re.get(j).getPeso()));
            jLabelCTipo3.setText(re.get(j).getTipo1().getTipo());
            jLabelCTipo4.setText(re.get(j).getTipo2().getTipo());
            jLabelCEspecie1.setText(re.get(j).getCategoria().getCategoria());
            jLabelCHabitat.setText(re.get(j).getTipo1().getHabitat());
            jTextCDesc1.setText(re.get(j).getDesc());
            System.out.println(re.get(j));
            j++;
        }
    }//GEN-LAST:event_bNext1ActionPerformed

    private void bBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBack1ActionPerformed
        if (j >= re.size() || j < 0) {
            j = re.size() - 1;
        }
        if (j >= 0 && j < re.size()) {

            JlabellImage1.setIcon(re.get(j).getFoto());
            jLabelCId1.setText(String.valueOf(re.get(j).getId()));
            jLabelCNome1.setText(re.get(j).getNome());
            jLabelCAltura1.setText(String.valueOf(re.get(j).getAltura()));
            jLabelCPeso1.setText(String.valueOf(re.get(j).getPeso()));
            jLabelCTipo3.setText(re.get(j).getTipo1().getTipo());
            jLabelCTipo4.setText(re.get(j).getTipo2().getTipo());
            jLabelCEspecie1.setText(re.get(j).getCategoria().getCategoria());
            jLabelCHabitat.setText(re.get(j).getTipo1().getHabitat());
            jTextCDesc1.setText(re.get(j).getDesc());
            j--;
        }
    }//GEN-LAST:event_bBack1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jInternalFrame3.setVisible(true);
        jInternalFrame4.setVisible(false);
        jTextId1.setText((String.valueOf(re.get(0).getId())));
        jTextNome1.setText(re.get(0).getNome());
        jTextAltura1.setText(String.valueOf(re.get(0).getAltura()));
        jTextPeso1.setText(String.valueOf(re.get(0).getPeso()));
        jTextDesc1.setText(re.get(0).getDesc());
        jLabelCHabitat.setText(re.get(0).getTipo1().getHabitat());
        lImagem1.setIcon(re.get(0).getFoto());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void bMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenu1ActionPerformed
        JlabellImage1.setIcon(null);
        jTextId1.setText("");
        jTextNome1.setText("");
        jTextAltura1.setText("");
        jTextPeso1.setText("");
        jTextDesc1.setText("");
        jLabelCHabitat.setText("");
        lImagem1.setIcon(null);
        jInternalFrame4.setVisible(false);
    }//GEN-LAST:event_bMenu1ActionPerformed
    int j= 0; 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface1.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface1.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface1.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface1.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabellImage;
    private javax.swing.JLabel JlabellImage1;
    private javax.swing.JButton bBack;
    private javax.swing.JButton bBack1;
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bCadastrar1;
    private javax.swing.JButton bImagem;
    private javax.swing.JButton bImagem1;
    private javax.swing.JButton bMenu;
    private javax.swing.JButton bMenu1;
    private javax.swing.JButton bNext;
    private javax.swing.JButton bNext1;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonClasse;
    private javax.swing.JButton jButtonEspecie;
    private javax.swing.JButton jButtonHabitat;
    private javax.swing.JButton jButtonMenu;
    private javax.swing.JButton jButtonNome;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboTipo1;
    private javax.swing.JComboBox<String> jComboTipo2;
    private javax.swing.JComboBox<String> jComboTipo3;
    private javax.swing.JComboBox<String> jComboTipo4;
    private javax.swing.JFrame jFramePesquisa;
    private javax.swing.JInternalFrame jFramePesquisaEspecie;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabeNome;
    private javax.swing.JLabel jLabeNome1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelAltura1;
    private javax.swing.JLabel jLabelAltura2;
    private javax.swing.JLabel jLabelAltura3;
    private javax.swing.JLabel jLabelCAltura;
    private javax.swing.JLabel jLabelCAltura1;
    private javax.swing.JLabel jLabelCEspecie;
    private javax.swing.JLabel jLabelCEspecie1;
    private javax.swing.JLabel jLabelCHabitat;
    private javax.swing.JLabel jLabelCHabitat1;
    private javax.swing.JLabel jLabelCId;
    private javax.swing.JLabel jLabelCId1;
    private javax.swing.JLabel jLabelCNome;
    private javax.swing.JLabel jLabelCNome1;
    private javax.swing.JLabel jLabelCPeso;
    private javax.swing.JLabel jLabelCPeso1;
    private javax.swing.JLabel jLabelCTipo1;
    private javax.swing.JLabel jLabelCTipo2;
    private javax.swing.JLabel jLabelCTipo3;
    private javax.swing.JLabel jLabelCTipo4;
    private javax.swing.JLabel jLabelCat;
    private javax.swing.JLabel jLabelCat1;
    private javax.swing.JLabel jLabelDec;
    private javax.swing.JLabel jLabelDec1;
    private javax.swing.JLabel jLabelEspecie;
    private javax.swing.JLabel jLabelEspecie1;
    private javax.swing.JLabel jLabelHabitat;
    private javax.swing.JLabel jLabelHabitat1;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelID1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelPeso1;
    private javax.swing.JLabel jLabelPeso2;
    private javax.swing.JLabel jLabelPeso3;
    private javax.swing.JLabel jLabelPesqNome;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipo1;
    private javax.swing.JLabel jLabelTipo2;
    private javax.swing.JLabel jLabelTipo3;
    private javax.swing.JLabel jLabelTipo4;
    private javax.swing.JLabel jLabelTipo5;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListaNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextAltura;
    private javax.swing.JTextField jTextAltura1;
    private javax.swing.JTextArea jTextCDesc;
    private javax.swing.JTextArea jTextCDesc1;
    private javax.swing.JTextArea jTextDesc;
    private javax.swing.JTextArea jTextDesc1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldPesqNome;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextId1;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNome1;
    private javax.swing.JTextField jTextPeso;
    private javax.swing.JTextField jTextPeso1;
    private javax.swing.JLabel lImagem;
    private javax.swing.JLabel lImagem1;
    // End of variables declaration//GEN-END:variables
}

